### Part 1: Theoretical Questions

1. **Different Data Structures in TensorFlow:**
   - **Tensor:** The primary data structure in TensorFlow, representing multi-dimensional arrays. Examples include scalar (0-D tensor), vector (1-D tensor), matrix (2-D tensor), and higher-dimensional tensors.
   - **Variable:** A special type of tensor that maintains its value across multiple calls to the computational graph. Used for trainable parameters in models.
   - **Placeholder:** Deprecated in TensorFlow 2.x, placeholders were used to feed data into the computational graph during runtime.
   - **SparseTensor:** Efficient representation of sparse data, containing indices, values, and dense shape.
   - **RaggedTensor:** Represents nested variable-length lists of tensors, useful for sequences with varying lengths.
   - **Dataset:** Represents a sequence of elements, commonly used for data input pipelines in TensorFlow.

2. **Difference between TensorFlow Constant and Variable:**
   - **Constant:** TensorFlow constants are immutable tensors whose values cannot be changed during execution. They are initialized with a fixed value and remain constant throughout the execution of the computational graph.
     ```python
     import tensorflow as tf
     constant_tensor = tf.constant([1, 2, 3])
     ```
   - **Variable:** TensorFlow variables are mutable tensors whose values can be changed during execution. They are typically used to represent model parameters that need to be updated during training.
     ```python
     import tensorflow as tf
     variable_tensor = tf.Variable([1, 2, 3])
     ```

3. **Matrix Operations in TensorFlow:**
   - **Matrix Addition:** Use the `tf.add()` function to perform element-wise addition between two matrices.
     ```python
     import tensorflow as tf
     matrix_a = tf.constant([[1, 2], [3, 4]])
     matrix_b = tf.constant([[5, 6], [7, 8]])
     result = tf.add(matrix_a, matrix_b)
     ```
   - **Matrix Multiplication:** Use the `tf.matmul()` function to perform matrix multiplication between two matrices.
     ```python
     import tensorflow as tf
     matrix_a = tf.constant([[1, 2], [3, 4]])
     matrix_b = tf.constant([[5, 6], [7, 8]])
     result = tf.matmul(matrix_a, matrix_b)
     ```
   - **Element-wise Operations:** TensorFlow supports element-wise operations on tensors. For example, you can use operators like `+`, `-`, `*`, `/` to perform element-wise addition, subtraction, multiplication, and division.
     ```python
     import tensorflow as tf
     tensor_a = tf.constant([1, 2, 3])
     tensor_b = tf.constant([4, 5, 6])
     result = tensor_a * tensor_b  # Element-wise multiplication
 

# Part 2

In [4]:
import tensorflow as tf

In [17]:
import tensorflow as tf

# 1. Create a normal matrix A with dimensions 3x3
A = tf.random.normal([3, 3])
print("Matrix A:")
print(A)

# 2. Create a Gaussian matrix B with dimensions 3x3
B = tf.random.truncated_normal([3, 3])
print("\nMatrix B:")
print(B)

# 3. Create a matrix C with dimensions 2x3, mean=3, std=0.5
C = tf.random.normal([2, 3], mean=3, stddev=0.5)
print("\nMatrix C:")
print(C)

# 4. Perform matrix addition between A and B, store in D
D = A + B
print("\nMatrix D (A + B):")
print(D)

# 5. Perform matrix multiplication between C and D, store in E
E = tf.matmul(C, D)
print("\nMatrix E (C * D):")
print(E)

Matrix A:
tf.Tensor(
[[ 0.47787273  2.2578528  -0.33716187]
 [ 1.384392   -1.1506196  -2.0118773 ]
 [-0.56479734 -1.7211028  -0.19370215]], shape=(3, 3), dtype=float32)

Matrix B:
tf.Tensor(
[[ 1.2687714   0.4110415  -0.5349112 ]
 [-0.289515   -0.2676244   0.00987281]
 [-0.31864566 -1.4187199   0.17212878]], shape=(3, 3), dtype=float32)

Matrix C:
tf.Tensor(
[[3.0673277 2.7918506 3.3308213]
 [3.4725256 2.5034797 2.4433944]], shape=(2, 3), dtype=float32)

Matrix D (A + B):
tf.Tensor(
[[ 1.7466441   2.6688943  -0.87207305]
 [ 1.094877   -1.418244   -2.0020044 ]
 [-0.883443   -3.1398227  -0.02157336]], shape=(3, 3), dtype=float32)

Matrix E (C * D):
tf.Tensor(
[[ 5.471672  -6.2313395 -8.336088 ]
 [ 6.647669  -1.9545665 -8.092986 ]], shape=(2, 3), dtype=float32)
